#GENERATED BY GEMINI
# Use a lightweight Nginx image as the base
FROM nginx:alpine

# Copy your website files into the Nginx public directory
COPY . /usr/share/nginx/html

# Expose port 80 (Nginx's default)
EXPOSE 80

# Command to run Nginx when the container starts (default for nginx:alpine)
CMD ["nginx", "-g", "daemon off;"]
